# Generated by Django 2.2.12 on 2020-05-25 04:54

import cloudinary.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bee_cate_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=6)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='bee_story_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=12)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('name1', models.CharField(max_length=20)),
                ('co1', models.CharField(max_length=30)),
                ('name2', models.CharField(max_length=20)),
                ('co2', models.CharField(max_length=30)),
                ('name3', models.CharField(max_length=20)),
                ('co3', models.CharField(max_length=30)),
                ('post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techbee.bee_cate_model')),
            ],
        ),
        migrations.AlterField(
            model_name='categories_model',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/hm9k6tunn/image/upload/v1589727150/defo_ebe9rs.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event_model',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/hm9k6tunn/image/upload/v1589727150/defo_ebe9rs.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='parts_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/hm9k6tunn/image/upload/v1589727150/defo_ebe9rs.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='like_point',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/hm9k6tunn/image/upload/v1589727150/defo_ebe9rs.jpg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='plofile',
            field=models.TextField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.DeleteModel(
            name='bee_model',
        ),
        migrations.DeleteModel(
            name='tech_bee_model',
        ),
    ]
