# Generated by Django 3.0.1 on 2020-03-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_meta',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
