# Generated by Django 3.0.1 on 2020-03-19 13:26

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0003_auto_20200319_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_meta',
            name='name',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=20, null=True),
        ),
    ]
