# Generated by Django 3.0.1 on 2020-03-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0004_auto_20200319_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_model',
            name='css_code',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='parts_model',
            name='html_code',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='plofile',
            field=models.TextField(max_length=220),
        ),
    ]
