# Generated by Django 3.0.1 on 2020-03-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0005_auto_20200320_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts_model',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
