# Generated by Django 3.0.1 on 2020-03-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0006_parts_model_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts_model',
            name='video',
            field=models.FileField(default='', upload_to='media/'),
        ),
    ]
