# Generated by Django 3.0.1 on 2020-03-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0008_like_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories_model',
            name='img',
            field=models.ImageField(default='media/defo.jpg', upload_to='media/'),
        ),
    ]
