# Generated by Django 3.0.1 on 2020-03-23 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0009_categories_model_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite_model',
            name='favorite_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
