# Generated by Django 3.0.1 on 2020-03-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0010_favorite_model_favorite_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_model',
            name='categories',
            field=models.CharField(max_length=30),
        ),
    ]
