# Generated by Django 3.0.1 on 2020-03-23 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0011_auto_20200323_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_model',
            name='like_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
