# Generated by Django 3.0.1 on 2020-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0017_auto_20200328_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_meta',
            name='qrcode',
            field=models.ImageField(default='media/defo.jpg', upload_to='media/'),
        ),
    ]
