# Generated by Django 3.0.1 on 2020-04-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0023_auto_20200403_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel_model',
            name='username',
        ),
        migrations.RemoveField(
            model_name='favorite_model',
            name='part_id',
        ),
        migrations.RemoveField(
            model_name='like_model',
            name='part_id',
        ),
    ]
