# Generated by Django 3.0.1 on 2020-04-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0024_auto_20200403_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel_model',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='favorite_model',
            name='part_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='like_model',
            name='part_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
