# Generated by Django 3.0.1 on 2020-04-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0025_auto_20200403_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel_model',
            old_name='username',
            new_name='usernamey',
        ),
    ]
