# Generated by Django 3.0.1 on 2020-04-03 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techbee', '0027_auto_20200403_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_model',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite_model',
            name='part_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techbee.parts_model'),
        ),
        migrations.AlterField(
            model_name='like_model',
            name='part_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='techbee.parts_model'),
        ),
    ]
