# Generated by Django 3.0.1 on 2020-04-08 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0028_auto_20200403_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='media/defo.jpg', upload_to='media/')),
                ('event_name', models.CharField(max_length=15)),
                ('event_date', models.CharField(max_length=15)),
                ('event_time', models.CharField(max_length=15)),
                ('event_venue', models.CharField(max_length=30)),
                ('set_event', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
