# Generated by Django 3.0.1 on 2020-04-12 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0029_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_meta',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
