# Generated by Django 3.0.1 on 2020-04-12 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0032_auto_20200413_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_meta',
            name='last_login',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
