# Generated by Django 3.0.1 on 2020-04-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0034_event_img_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afirieito_model',
            name='status',
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='plofile',
            field=models.TextField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='qrcode',
            field=models.CharField(max_length=30),
        ),
    ]
