# Generated by Django 3.0.1 on 2020-04-14 23:31

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0035_auto_20200414_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_meta',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='name',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=20),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='plofile',
            field=models.TextField(default='', max_length=220),
        ),
    ]
