# Generated by Django 3.0.1 on 2020-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0036_auto_20200414_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_meta',
            name='position',
            field=models.CharField(default='mem', max_length=10),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
