# Generated by Django 3.0.1 on 2020-04-22 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0042_auto_20200422_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_class_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_c', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='footer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=1000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='techbee.footer_class_model')),
            ],
        ),
    ]
