# Generated by Django 3.0.1 on 2020-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0043_footer_class_model_footer_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer_model',
            name='category',
        ),
        migrations.AddField(
            model_name='footer_model',
            name='footer_cat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='footer_class_model',
        ),
    ]
