# Generated by Django 3.0.1 on 2020-04-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0044_auto_20200423_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_cat_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_cat', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='footer_model',
            name='footer_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='techbee.footer_cat_model'),
        ),
    ]
