# Generated by Django 3.0.1 on 2020-04-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0045_auto_20200423_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_model',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
