# Generated by Django 3.0.1 on 2020-04-24 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0046_footer_model_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_meta',
            name='give_like',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
