# Generated by Django 3.0.1 on 2020-04-24 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0048_auto_20200424_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech_bee_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tech_teaching_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tech_tube_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tube_movie_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('video', models.FileField(default='', upload_to='media/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('text', models.TextField(max_length=2000)),
                ('post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='techbee.tech_tube_model')),
            ],
        ),
        migrations.CreateModel(
            name='teaching_movie_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('video', models.FileField(default='', upload_to='media/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('text', models.TextField(max_length=2000)),
                ('post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='techbee.tech_teaching_model')),
            ],
        ),
        migrations.CreateModel(
            name='bee_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('text', models.TextField(max_length=2000)),
                ('post_time', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='techbee.tech_bee_model')),
            ],
        ),
    ]
