# Generated by Django 3.0.1 on 2020-04-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0049_bee_model_teaching_movie_model_tech_bee_model_tech_teaching_model_tech_tube_model_tube_movie_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_bee_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tech_teaching_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tech_tube_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
