# Generated by Django 3.0.1 on 2020-04-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0050_auto_20200424_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_meta',
            name='position',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
