# Generated by Django 3.0.6 on 2020-05-13 05:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0051_auto_20200430_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bee_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='categories_model',
            name='img',
            field=cloudinary.models.CloudinaryField(default='static/base/defo.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event_img_model',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event_model',
            name='img',
            field=cloudinary.models.CloudinaryField(default='static/base/defo.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='footer_model',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='parts_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='parts_model',
            name='video',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='teaching_movie_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='teaching_movie_model',
            name='video',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='tech_bee_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tech_teaching_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tech_tube_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tube_movie_model',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='tube_movie_model',
            name='video',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='user_meta',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='static/base/defo.jpg', max_length=255, verbose_name='image'),
        ),
    ]
