# Generated by Django 3.0.6 on 2020-05-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0053_auto_20200513_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts_model',
            name='css_code',
        ),
        migrations.RemoveField(
            model_name='parts_model',
            name='html_code',
        ),
        migrations.RemoveField(
            model_name='parts_model',
            name='video',
        ),
        migrations.RemoveField(
            model_name='teaching_movie_model',
            name='video',
        ),
        migrations.RemoveField(
            model_name='tube_movie_model',
            name='video',
        ),
        migrations.AddField(
            model_name='parts_model',
            name='codepen',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='parts_model',
            name='text',
            field=models.TextField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
