# Generated by Django 3.0.6 on 2020-05-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbee', '0054_auto_20200514_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories_model',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
